repos:
  # flake8
  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        args: ["--ignore=W504, W503", "--max-line-length=248"]
        exclude: ^(try_nvp.py)$|^(videoswap/thinplate_utils/.*)$|^(scripts/atlas_scripts/only_evaluate.py)$|^(scripts/atlas_scripts/only_edit.py)$|^(videoswap/ddpm_inversion/ddpm_inv_util.py)$|^(test_animatediff.py)$|^(videoswap/utils/convert_lora_safetensor_to_diffusers.py)$|^videoswap/models/animatediff_models/.*\.py$

  # modify known_third_party
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config

  # isort
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--line-length=120]

  # yapf
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.30.0
    hooks:
      - id: yapf
        args: [--style, "{based_on_style: pep8, column_limit: 248}"]

  # pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace  # Trim trailing whitespace
      - id: check-yaml  # Attempt to load all yaml files to verify syntax
      - id: check-merge-conflict  # Check for files that contain merge conflict strings
      - id: double-quote-string-fixer  # Replace double quoted strings with single quoted strings
      - id: end-of-file-fixer  # Make sure files end in a newline and only a newline
      - id: requirements-txt-fixer  # Sort entries in requirements.txt and remove incorrect entry for pkg-resources==0.0.0
      - id: fix-encoding-pragma  # Remove the coding pragma: # -*- coding: utf-8 -*-
        args: ["--remove"]
      - id: mixed-line-ending  # Replace or check mixed line ending
        args: ["--fix=lf"]
